services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./:/var/app
      - deps:/var/app/deps
    environment:
      DATABASE_HOST: "database"
      DATABASE_PORT: "5432"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "postgres"
      DATABASE_NAME: "phoenix_sample_dev"
      TZ: "Asia/Tokyo"
    ports:
      - "4000:4000"
    depends_on:
      - database
    command: sh -c 'mix deps.get && mix compile && mix phx.server'
  database:
    image: postgres:14.4
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: "phoenix_sample_dev"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

volumes:
  deps:
