version: "3.5"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./:/var/app
      - deps:/var/app/deps
    environment:
      DATABASE_HOST: "database"
      DATABASE_NAME: "phoenix_sample_dev"
      TZ: "Asia/Tokyo"
    ports:
      - "4000:4000"
    depends_on:
      - database
    tty: true
    command: sh -c 'mix deps.get && mix compile && mix phx.server'
  database:
    image: mysql:8.0.23
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "phoenix_sample_dev"
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --default-authentication-plugin=mysql_native_password

volumes:
  deps:
