name: Build

on: push

env:
  SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}

jobs:
  backend:
    name: Test
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.23
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: phoenix_sample_test
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      MIX_ENV: "test"
      DATABASE_NAME_TEST: "phoenix_sample_test"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Erlang and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 24.3.1
          elixir-version: 1.13.3
      - name: Cache dependencies
        uses: actions/cache@v2
        id: app-cache
        with:
          path: deps
          key: ${{ runner.OS }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Get dependencies
        if: ${{ steps.app-cache.outputs.cache-hit != 'true' }}
        run: mix deps.get
      - name: Run setup
        run: mix ecto.create
      - name: Run test
        run: mix test
